repository: jdoscher/jdoscher.github.io
title: "Doscher"
url: "https://doscher.net"   # switch to doscher.com later
baseurl: ""
markdown: kramdown
theme: minima

title: "Doscher"
url: "https://doscher.net"   # use doscher.com after cutover
baseurl: ""

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Make anything under posts/ render with the post layout and a /posts/slug/ URL
defaults:
  - scope:
      path: "posts"
    values:
      layout: post
      permalink: /posts/:slug/
      sitemap: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

defaults:
  - scope:
      path: "posts"
      type: posts
    values:
      layout: post
      sitemap: true

# Optional: nicer feeds & sitemap
feed:
  collections:
    - posts
